import type { ContentBlock } from "@/lib/blog/types";

export const screenFreeActivitiesContent: ContentBlock[] = [
  {
    type: "p",
    text: "The hardest part of screen-free time usually isn't finding something to do — it's the first restless ten minutes before a child settles into doing it. Once that initial friction passes, almost any screen-free activity does something a screen genuinely can't: it puts you and your child in the same physical and emotional space, responding to each other in real time.",
  },
  {
    type: "p",
    text: "This isn't a list to get through perfectly or all at once. It's a deep well to dip into on the evenings and weekends when you're out of ideas and want something that builds connection rather than just filling time.",
  },
  { type: "h2", id: "why-it-matters", text: "Why Screen-Free Time Together Matters More Than the Activity" },
  { type: "h3", id: "connection-doesnt-require-entertainment", text: "Connection Doesn't Require Entertainment" },
  {
    type: "p",
    text: "Research on parent-child **synchrony** — the responsive, back-and-forth attunement between a parent and child during play — consistently links it to secure attachment and stronger emotional regulation, building on the foundational attachment research of John Bowlby and Mary Ainsworth. A screen, by design, can't be responsive to your child the way you can. It can be more dazzling in the moment, but it can't notice your child's specific joke, adjust the game because they seem tired, or reflect their excitement back at them — and that responsiveness, not the entertainment value, is what the connection actually runs on.",
  },
  {
    type: "p",
    text: "Researcher Peter Gray has written extensively about the decline of unstructured, child-led play over recent decades, and the developmental costs that may come with it — including effects on problem-solving and emotional resilience. Many of the activities below lean toward open-ended, child-led play for exactly this reason, rather than activities that simply replace one form of entertainment with another. For more on the specific research comparing screens and reading, see [our deeper look at what's happening inside a child's brain](/blog/screen-time-vs-reading-childs-brain).",
  },
  { type: "divider", icon: "🌿" },
  { type: "h2", id: "fifty-activities", text: "50 Screen-Free Activities, Organized by Type" },
  { type: "h3", id: "quick-connection-moments", text: "Quick Connection Moments (5 Minutes or Less)" },
  {
    type: "ol",
    items: [
      "Two truths and a wish — share two true things and one thing you wish were true.",
      "A round of \"good part / hard part\" from today.",
      "Thumb war or rock-paper-scissors best of five.",
      "Tell a one-sentence story together, taking turns adding a line.",
      "A staring contest with silly faces allowed.",
      "Guess the song from a hum.",
      "Trade compliments — one for each person in the room.",
      "A quick shoulder or hand massage while chatting.",
      "Name three things you're grateful for, fast.",
      "A made-up secret handshake.",
    ],
  },
  { type: "h3", id: "active-and-outdoor-play", text: "Active & Outdoor Play" },
  {
    type: "ul",
    items: [
      "Sidewalk chalk obstacle course",
      "A neighborhood scavenger hunt with a simple list",
      "Backyard or park frisbee",
      "An evening walk with no destination",
      "Bike or scooter ride together",
      "A simple nature \"collect five things\" walk",
      "Jump rope or hopscotch",
      "A water balloon toss",
      "Building a fort from cushions or blankets",
      "Stargazing and naming made-up constellations",
    ],
  },
  { type: "h3", id: "creative-and-imaginative-play", text: "Creative & Imaginative Play" },
  {
    type: "ul",
    items: [
      "Puppet show with socks or paper bags",
      "Drawing each other's portraits, badly, on purpose",
      "Building a marble run or block tower together",
      "Writing and illustrating a tiny family comic",
      "Inventing a new recipe for an imaginary restaurant",
      "Acting out a favorite book's ending differently",
      "A family band with pots, pans, and kazoos",
      "Designing a treasure map for a hunt later",
      "Clay or dough sculpting contest",
      "Making up a superhero alter-ego for each family member",
    ],
  },
  { type: "h3", id: "quiet-together-time", text: "Quiet Together Time" },
  {
    type: "ul",
    items: [
      "Reading the same book side by side",
      "A jigsaw puzzle left out to chip away at over a week",
      "Sorting and organizing a junk drawer together",
      "A card game like Go Fish or Uno",
      "Coloring the same page together, different sections",
      "Listening to an audio story under a blanket",
      "Pressing flowers or leaves from a walk",
      "Sorting old photos and telling the stories behind them",
      "A simple memory or matching game",
      "Quiet side-by-side journaling or drawing",
    ],
  },
  { type: "h3", id: "family-traditions-and-rituals", text: "Family Traditions & Rituals" },
  {
    type: "ul",
    items: [
      "A recurring \"breakfast for dinner\" night",
      "A weekly family meeting with snacks",
      "A seasonal photo taken in the same spot every year",
      "A rotating \"pick the activity\" turn for each family member",
      "A simple family flag or crest designed together",
      "An annual \"family awards\" night, silly categories encouraged",
      "A shared family playlist everyone gets to add to",
      "A no-particular-occasion celebration dinner",
      "A yearly time capsule letter to next year's family",
      "A bedtime phrase or song that's just yours",
    ],
  },
  { type: "divider", icon: "🧭" },
  {
    type: "pullquote",
    text: "The specific activity matters far less than the fact that, for these minutes, you're both responding to the same thing — together, in real time, with nothing else competing for either of your attention.",
  },
  {
    type: "callout",
    variant: "research",
    label: "🔬 What the Research Shows",
    text: "Research on parent-child synchrony during play has linked responsive, attuned interaction to stronger emotional regulation and more secure attachment — benefits tied to the quality of attention exchanged, not to any particular toy or activity.",
  },
  { type: "h2", id: "making-it-stick", text: "Making Screen-Free Time Stick Without a Fight" },
  {
    type: "p",
    text: "The activities above work best when they replace a small, specific window rather than becoming a vague all-day mandate — the hour after school, or the half hour before dinner, for instance. Children (and honestly, adults) resist open-ended restrictions far more than a clear, bounded swap: \"after this episode, we're doing chalk outside\" tends to land better than \"no more screens today.\"",
  },
  {
    type: "callout",
    variant: "parent-tip",
    label: "💡 Parent Tip",
    text: "Let your child pick from a short list rather than facing an open-ended \"go play.\" Three or four specific options from this list ahead of time removes the decision fatigue that often leads everyone back to a screen by default.",
  },
  { type: "divider", icon: "✦" },
  {
    type: "callout",
    variant: "family-activity",
    label: "🧭 Family Activity",
    text: "This week, pick three activities from the list above and write them on sticky notes by the TV remote or tablet charger — a visible, ready-made alternative removes the friction of having to think of one in the moment.",
  },
  {
    type: "p",
    text: "A few of these naturally turn into [family traditions](/blog/family-traditions-for-children) if you let them repeat, and several double as quiet practice in the same [character traits](/blog/character-development-for-children) — patience, creativity, kindness — that a five-minute screen rarely builds the same way.",
  },
  { type: "h2", id: "faq", text: "Frequently Asked Questions" },
];
